version: "3.8"

services:
    frontend:
        build: ../frontend
        image: just-frontend
        ports: 
            - 3001:3000
    database:
        image: mysql/mysql-server
        ports: 
            - 33061:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wearejustpros
            MYSQL_DATABASE: just
            MYSQL_USER: root
            MYSQL_PASSWORD: wearejustpros