version: "3.8"

services:
    backend:
        build: ../backend
        ports:
            - 8080:80
    database:
        image: mysql/mysql-server
        ports: 
            - 33061:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wearejustpros
            MYSQL_DATABASE: just
            MYSQL_USER: root
            MYSQL_PASSWORD: wearejustpros